// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Baufon: typeof import('./components/projects/Baufon.vue')['default']
    Creartive: typeof import('./components/projects/Creartive.vue')['default']
    Date: typeof import('./components/date/Date.vue')['default']
    DateRange: typeof import('./components/date/DateRange.vue')['default']
    Dot: typeof import('./components/Dot.vue')['default']
    Facts: typeof import('./components/Facts.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Keenscreen: typeof import('./components/projects/Keenscreen.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Showcase: typeof import('./components/Showcase.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SimpleIconsArtstation: typeof import('~icons/simple-icons/artstation')['default']
    SimpleIconsDeviantart: typeof import('~icons/simple-icons/deviantart')['default']
    SimpleIconsLinkedin: typeof import('~icons/simple-icons/linkedin')['default']
    SimpleIconsXing: typeof import('~icons/simple-icons/xing')['default']
    Spacer: typeof import('./components/Spacer.vue')['default']
    TrackingComp: typeof import('./components/projects/TrackingComp.vue')['default']
    Wrapper: typeof import('./components/Wrapper.vue')['default']
  }
}
