// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Date: typeof import('./components/date/Date.vue')['default']
    DateRange: typeof import('./components/date/DateRange.vue')['default']
    Dot: typeof import('./components/Dot.vue')['default']
    Facts: typeof import('./components/Facts.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Spacer: typeof import('./components/Spacer.vue')['default']
    Wrapper: typeof import('./components/Wrapper.vue')['default']
  }
}

export {}
