name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version-file: .node-version
      - name: Build, check, and lint
        run: pnpm run ci
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
      - name: Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
