name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DerYeger/pnpm-setup-action@master
        with:
          node-version-file: .node-version
      - name: Build, check, and lint
        run: pnpm run ci
